name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          black: true

      - name: Flake8
        uses: microsoft/action-python@0.7.0
        with:          
          flake8: true

  testing:
    runs-on: ubuntu-latest
    steps:    
      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:          
          testing: true
